// Code generated by goyacc -o sql.go sql.y. DO NOT EDIT.

//line sql.y:6
package sqlparser

import __yyfmt__ "fmt"

//line sql.y:6

import (
	"bytes"
)

func SetParseTree(yylex interface{}, stmt Statement) {
	yylex.(*Tokenizer).ParseTree = stmt
}

func getStatementStart(yylex interface{}) int {
	return yylex.(*Tokenizer).GetAndPopStatementStart()
}

func SetAllowComments(yylex interface{}, allow bool) {
	yylex.(*Tokenizer).AllowComments = allow
}

func GetCurrentPos(yylex interface{}) int {
	return yylex.(*Tokenizer).Position
}

func ForceEOF(yylex interface{}) {
	yylex.(*Tokenizer).ForceEOF = true
}

var (
	SHARE        = []byte("share")
	MODE         = []byte("mode")
	IF_BYTES     = []byte("if")
	VALUES_BYTES = []byte("values")
)

//line sql.y:43
type yySymType struct {
	yys                  int
	empty                struct{}
	statement            Statement
	statements           Statements
	selStmt              SelectStatement
	byt                  byte
	bytes                []byte
	bytes2               [][]byte
	str                  string
	selectExprs          SelectExprs
	selectExpr           SelectExpr
	columns              Columns
	colName              *ColName
	tableExprs           TableExprs
	tableExpr            TableExpr
	smTableExpr          SimpleTableExpr
	tableName            *TableName
	indexHints           *IndexHints
	expr                 Expr
	boolExpr             BoolExpr
	valExpr              ValExpr
	colTuple             ColTuple
	valExprs             ValExprs
	values               Values
	rowTuple             RowTuple
	subquery             *Subquery
	caseExpr             *CaseExpr
	whens                []*When
	when                 *When
	orderBy              OrderBy
	order                *Order
	limit                *Limit
	insRows              InsertRows
	updateExprs          UpdateExprs
	updateExpr           *UpdateExpr
	position             int
	positionedStatements PositionedStatements
}

const LEX_ERROR = 57346
const SELECT = 57347
const INSERT = 57348
const UPDATE = 57349
const DELETE = 57350
const FROM = 57351
const WHERE = 57352
const GROUP = 57353
const HAVING = 57354
const ORDER = 57355
const BY = 57356
const LIMIT = 57357
const FOR = 57358
const ALL = 57359
const DISTINCT = 57360
const AS = 57361
const EXISTS = 57362
const IN = 57363
const IS = 57364
const LIKE = 57365
const BETWEEN = 57366
const NULL = 57367
const ASC = 57368
const DESC = 57369
const VALUES = 57370
const INTO = 57371
const DUPLICATE = 57372
const KEY = 57373
const DEFAULT = 57374
const SET = 57375
const LOCK = 57376
const KEYRANGE = 57377
const ID = 57378
const STRING = 57379
const NUMBER = 57380
const VALUE_ARG = 57381
const LIST_ARG = 57382
const COMMENT = 57383
const LE = 57384
const GE = 57385
const NE = 57386
const NULL_SAFE_EQUAL = 57387
const UNION = 57388
const MINUS = 57389
const EXCEPT = 57390
const INTERSECT = 57391
const JOIN = 57392
const STRAIGHT_JOIN = 57393
const LEFT = 57394
const RIGHT = 57395
const INNER = 57396
const OUTER = 57397
const CROSS = 57398
const NATURAL = 57399
const USE = 57400
const FORCE = 57401
const ON = 57402
const OR = 57403
const AND = 57404
const NOT = 57405
const UNARY = 57406
const CASE = 57407
const WHEN = 57408
const THEN = 57409
const ELSE = 57410
const END = 57411
const CREATE = 57412
const ALTER = 57413
const DROP = 57414
const RENAME = 57415
const ANALYZE = 57416
const TABLE = 57417
const INDEX = 57418
const VIEW = 57419
const TO = 57420
const IGNORE = 57421
const IF = 57422
const UNIQUE = 57423
const USING = 57424
const SHOW = 57425
const DESCRIBE = 57426
const EXPLAIN = 57427

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"SELECT",
	"INSERT",
	"UPDATE",
	"DELETE",
	"FROM",
	"WHERE",
	"GROUP",
	"HAVING",
	"ORDER",
	"BY",
	"LIMIT",
	"FOR",
	"ALL",
	"DISTINCT",
	"AS",
	"EXISTS",
	"IN",
	"IS",
	"LIKE",
	"BETWEEN",
	"NULL",
	"ASC",
	"DESC",
	"VALUES",
	"INTO",
	"DUPLICATE",
	"KEY",
	"DEFAULT",
	"SET",
	"LOCK",
	"KEYRANGE",
	"ID",
	"STRING",
	"NUMBER",
	"VALUE_ARG",
	"LIST_ARG",
	"COMMENT",
	"LE",
	"GE",
	"NE",
	"NULL_SAFE_EQUAL",
	"'('",
	"'='",
	"'<'",
	"'>'",
	"'~'",
	"UNION",
	"MINUS",
	"EXCEPT",
	"INTERSECT",
	"','",
	"JOIN",
	"STRAIGHT_JOIN",
	"LEFT",
	"RIGHT",
	"INNER",
	"OUTER",
	"CROSS",
	"NATURAL",
	"USE",
	"FORCE",
	"ON",
	"OR",
	"AND",
	"NOT",
	"'&'",
	"'|'",
	"'^'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'.'",
	"UNARY",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"CREATE",
	"ALTER",
	"DROP",
	"RENAME",
	"ANALYZE",
	"TABLE",
	"INDEX",
	"VIEW",
	"TO",
	"IGNORE",
	"IF",
	"UNIQUE",
	"USING",
	"SHOW",
	"DESCRIBE",
	"EXPLAIN",
	"';'",
	"')'",
	"'$'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 656

var yyAct = [...]int16{
	100, 289, 380, 168, 251, 98, 165, 68, 97, 55,
	324, 3, 261, 185, 281, 242, 212, 32, 87, 343,
	69, 167, 96, 109, 387, 7, 387, 86, 387, 110,
	38, 39, 40, 41, 42, 105, 107, 108, 5, 56,
	57, 136, 194, 71, 142, 141, 76, 233, 287, 79,
	91, 70, 136, 83, 7, 60, 82, 298, 299, 300,
	301, 302, 136, 303, 304, 34, 35, 36, 37, 92,
	233, 389, 43, 388, 45, 386, 126, 259, 46, 231,
	359, 361, 74, 130, 78, 134, 127, 371, 313, 129,
	138, 48, 200, 49, 310, 286, 51, 52, 53, 275,
	370, 106, 169, 340, 369, 315, 170, 243, 75, 273,
	360, 198, 54, 50, 309, 201, 232, 234, 140, 71,
	142, 141, 71, 179, 189, 123, 183, 70, 119, 188,
	70, 142, 141, 174, 190, 317, 243, 125, 279, 65,
	207, 189, 187, 92, 204, 164, 166, 205, 77, 141,
	211, 355, 221, 219, 220, 206, 223, 224, 225, 226,
	227, 228, 229, 230, 282, 197, 199, 196, 152, 153,
	154, 155, 156, 121, 214, 154, 155, 156, 235, 92,
	92, 255, 71, 71, 282, 133, 357, 208, 356, 247,
	70, 249, 209, 210, 337, 256, 222, 250, 333, 240,
	237, 239, 246, 334, 117, 257, 336, 120, 298, 299,
	300, 301, 302, 254, 303, 304, 331, 266, 335, 135,
	235, 332, 186, 121, 268, 269, 34, 35, 36, 37,
	186, 233, 348, 267, 319, 265, 276, 253, 81, 264,
	272, 215, 122, 376, 375, 92, 214, 213, 374, 263,
	18, 284, 171, 103, 176, 288, 58, 278, 109, 175,
	181, 115, 285, 173, 292, 136, 274, 296, 104, 90,
	105, 107, 108, 182, 295, 121, 308, 312, 172, 95,
	177, 264, 77, 113, 72, 341, 316, 307, 71, 339,
	321, 263, 84, 265, 280, 139, 320, 322, 325, 314,
	350, 351, 94, 326, 306, 294, 111, 112, 88, 329,
	330, 293, 77, 116, 203, 202, 184, 338, 342, 131,
	128, 124, 66, 85, 344, 346, 265, 265, 114, 80,
	118, 6, 345, 318, 378, 64, 106, 18, 216, 271,
	217, 218, 385, 192, 149, 150, 151, 152, 153, 154,
	155, 156, 379, 132, 363, 325, 191, 365, 367, 364,
	245, 235, 63, 71, 59, 61, 290, 373, 354, 291,
	372, 70, 252, 353, 328, 381, 381, 381, 382, 383,
	238, 186, 103, 67, 384, 362, 390, 109, 391, 18,
	115, 392, 4, 193, 44, 258, 195, 104, 90, 105,
	107, 108, 47, 73, 366, 347, 368, 248, 95, 180,
	377, 349, 113, 323, 327, 277, 178, 241, 18, 102,
	149, 150, 151, 152, 153, 154, 155, 156, 99, 101,
	283, 94, 244, 103, 143, 111, 112, 88, 109, 93,
	352, 115, 116, 358, 262, 297, 260, 89, 104, 72,
	105, 107, 108, 103, 305, 137, 62, 114, 109, 95,
	33, 115, 31, 113, 236, 106, 17, 16, 104, 72,
	105, 107, 108, 15, 14, 13, 12, 11, 18, 95,
	10, 9, 94, 113, 8, 2, 111, 112, 1, 0,
	0, 0, 0, 116, 0, 0, 0, 0, 109, 0,
	0, 115, 94, 0, 0, 0, 111, 112, 114, 72,
	105, 107, 108, 116, 0, 0, 106, 0, 109, 171,
	0, 115, 0, 113, 18, 19, 20, 21, 114, 72,
	105, 107, 108, 0, 0, 0, 106, 0, 0, 171,
	0, 0, 0, 113, 0, 0, 111, 112, 0, 0,
	0, 0, 22, 116, 311, 0, 149, 150, 151, 152,
	153, 154, 155, 156, 0, 0, 111, 112, 114, 0,
	0, 0, 0, 116, 0, 270, 106, 149, 150, 151,
	152, 153, 154, 155, 156, 0, 0, 0, 114, 0,
	0, 0, 0, 0, 0, 0, 106, 0, 0, 144,
	148, 146, 147, 0, 23, 24, 26, 25, 27, 149,
	150, 151, 152, 153, 154, 155, 156, 28, 29, 30,
	160, 161, 162, 163, 0, 157, 158, 159, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 145, 149, 150,
	151, 152, 153, 154, 155, 156,
}

var yyPact = [...]int16{
	-1000, -1000, -63, 519, -1000, -1000, -1000, 175, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -18, -1, 23, 6, 22, -1000, -1000,
	-1000, 215, 519, 384, 348, -1000, -1000, -1000, 344, 306,
	286, 374, 248, -13, 17, 246, -1000, -6, 246, -1000,
	293, -39, 246, -39, 287, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 233, -1000, 286, 297, 50, 286, 168, -1000,
	195, -1000, 47, 285, 68, 246, -1000, -1000, 284, -1000,
	-10, 283, 333, 119, 246, -1000, 210, -1000, -1000, 276,
	40, 64, 578, -1000, 433, 413, -1000, -1000, -1000, 493,
	232, 217, -1000, 213, 208, -1000, 242, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 493, 227, 248, 280,
	371, 248, 493, 246, 337, 323, -55, -1000, 79, -1000,
	279, -1000, -1000, 278, -1000, -1000, 233, -1000, -1000, 246,
	112, 433, 433, 493, 201, 317, 493, 493, 127, 493,
	493, 493, 493, 493, 493, 493, 493, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 578, -23, 14, 15, 578,
	-1000, 473, 362, 233, -1000, 384, -2, -1000, 26, 539,
	332, 248, 248, 220, -1000, 359, 433, -1000, 539, -1000,
	-1000, 384, -1000, 115, 246, -1000, -16, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 203, -1000, -1000, -1000, -1000,
	81, 539, -1000, 473, -1000, -1000, 201, 493, 493, 539,
	507, -1000, 314, 95, 95, 95, 100, 100, -1000, -1000,
	-1000, -1000, -1000, 493, -1000, 539, -1000, 7, 233, -3,
	181, 55, -1000, 433, 98, 206, 175, 118, -7, -1000,
	359, 351, 355, 64, 175, 275, -1000, -1000, 269, -1000,
	212, 152, 268, 245, 36, -1000, -8, -1000, 539, 486,
	493, -1000, 539, -1000, -14, -1000, -2, 21, -1000, 493,
	53, -1000, 303, 179, -1000, -1000, -1000, 248, 351, -1000,
	493, 493, -1000, -1000, -1000, 363, 203, 203, -1000, -1000,
	160, 142, 162, 150, 138, -1000, -1000, 253, 1, 249,
	-1000, 493, 539, -1000, -83, -1000, 539, 493, 301, 206,
	-1000, -1000, 350, 177, -1000, 274, -1000, 361, 354, 152,
	85, -1000, 132, -1000, 130, -1000, -1000, -1000, 16, -1000,
	-1000, -1000, 539, -1000, 539, 378, -1000, 493, 493, -1000,
	-1000, -1000, 359, 433, 493, 433, -1000, -1000, -1000, 13,
	9, -4, 248, 539, -1000, 351, 64, 176, 64, 202,
	198, 197, 168, 318, 246, 246, 246, -1000, 377, 321,
	-27, -1000, -29, -31, -1000, 246, -1000, 246, -1000, -1000,
	246, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 488, 331, 485, 21, 484, 481, 480, 477, 476,
	475, 474, 473, 467, 466, 11, 462, 460, 456, 27,
	18, 455, 454, 447, 446, 12, 445, 444, 139, 443,
	2, 13, 440, 50, 439, 434, 432, 22, 6, 16,
	3, 430, 5, 429, 29, 428, 8, 419, 417, 15,
	416, 415, 414, 4, 413, 10, 411, 1, 410, 409,
	407, 14, 7, 20, 238, 403, 402, 396, 395, 394,
	393, 0, 9, 392,
}

var yyR1 = [...]int8{
	0, 1, 3, 3, 3, 3, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 4, 4, 4,
	5, 5, 6, 7, 8, 9, 9, 9, 9, 10,
	10, 10, 11, 12, 12, 12, 13, 14, 14, 14,
	73, 15, 16, 16, 17, 17, 17, 17, 17, 18,
	18, 19, 19, 20, 20, 20, 23, 23, 21, 21,
	21, 24, 24, 25, 25, 25, 25, 22, 22, 22,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 27,
	27, 27, 28, 28, 29, 29, 29, 29, 30, 30,
	31, 31, 33, 33, 33, 33, 33, 34, 34, 34,
	34, 34, 34, 34, 34, 34, 34, 34, 35, 35,
	35, 35, 35, 35, 35, 39, 39, 39, 44, 40,
	40, 38, 38, 38, 38, 38, 38, 38, 38, 38,
	38, 38, 38, 38, 38, 38, 38, 38, 43, 43,
	45, 45, 45, 47, 50, 50, 48, 48, 49, 51,
	51, 46, 46, 37, 37, 37, 37, 37, 52, 52,
	32, 32, 53, 53, 54, 54, 55, 56, 56, 56,
	57, 57, 57, 58, 58, 58, 59, 59, 60, 60,
	61, 61, 36, 36, 41, 41, 42, 42, 62, 62,
	63, 64, 64, 65, 65, 66, 66, 67, 67, 67,
	67, 67, 68, 68, 69, 69, 70, 70, 71, 72,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 4, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 13, 4, 3,
	7, 7, 8, 7, 3, 5, 7, 8, 4, 6,
	7, 4, 5, 4, 5, 5, 3, 2, 2, 2,
	0, 2, 0, 2, 1, 2, 1, 1, 1, 0,
	1, 1, 3, 1, 2, 3, 1, 1, 0, 1,
	2, 1, 3, 4, 3, 3, 5, 0, 1, 2,
	1, 1, 2, 3, 2, 3, 2, 2, 2, 1,
	3, 1, 1, 3, 0, 5, 5, 5, 1, 3,
	0, 2, 1, 3, 3, 2, 3, 3, 3, 4,
	3, 4, 5, 6, 3, 4, 2, 6, 1, 1,
	1, 1, 1, 1, 1, 3, 1, 1, 3, 1,
	3, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 2, 3, 4, 5, 4, 1, 1, 1,
	1, 1, 1, 5, 0, 1, 1, 2, 4, 0,
	2, 1, 3, 1, 2, 1, 1, 1, 0, 3,
	0, 2, 0, 3, 1, 3, 2, 0, 1, 1,
	0, 2, 4, 0, 2, 4, 0, 3, 1, 3,
	0, 5, 2, 1, 1, 3, 3, 1, 1, 3,
	3, 0, 2, 0, 3, 0, 1, 1, 1, 1,
	1, 1, 0, 1, 0, 1, 0, 2, 1, 0,
}

var yyChk = [...]int16{
	-1000, -1, -3, -15, -73, 101, -2, -4, -5, -6,
	-7, -8, -9, -10, -11, -12, -13, -14, 5, 6,
	7, 8, 33, 85, 86, 88, 87, 89, 98, 99,
	100, -16, -15, -17, 51, 52, 53, 54, -15, -15,
	-15, -15, -15, 90, -69, 92, 96, -66, 92, 94,
	90, 90, 91, 92, 90, -72, -72, -72, 41, -2,
	-4, 17, -18, 18, 29, -28, 36, 9, -62, -63,
	-46, -71, 36, -65, 95, 91, -71, 36, 90, -71,
	36, -64, 95, -71, -64, 36, -19, -20, 75, -23,
	36, -33, -38, -34, 69, 46, -37, -46, -42, -45,
	-71, -43, -47, 20, 35, 37, 103, 38, 39, 25,
	-44, 73, 74, 50, 95, 28, 80, -28, 33, 78,
	-28, 55, 47, 78, 36, 69, -71, -72, 36, -72,
	93, 36, 20, 66, -71, 9, 55, -21, -71, 19,
	78, 68, 67, -35, 21, 69, 23, 24, 22, 70,
	71, 72, 73, 74, 75, 76, 77, 47, 48, 49,
	42, 43, 44, 45, -33, -38, -33, -4, -40, -38,
	-38, 46, 46, 46, -44, 46, 46, 38, -50, -38,
	-59, 33, 46, -62, 36, -31, 10, -63, -38, -71,
	-72, 19, 20, -70, 97, -67, 88, 86, 32, 87,
	13, 36, 36, 36, -72, -15, -20, -71, 75, -33,
	-33, -38, -39, 46, -44, 40, 21, 23, 24, -38,
	-38, 25, 69, -38, -38, -38, -38, -38, -38, -38,
	-38, 102, 102, 55, 102, -38, 102, -19, 18, -19,
	-37, -48, -49, 81, -36, 28, -4, -62, -60, -46,
	-31, -53, 13, -33, -4, 66, -71, -72, -68, 93,
	-24, -25, -27, 46, 36, -44, -40, -39, -38, -38,
	68, 25, -38, 102, -19, 102, 55, -51, -49, 83,
	-33, -61, 66, -41, -42, -61, 102, 55, -53, -57,
	15, 14, -72, 36, 36, -31, 55, -26, 56, 57,
	58, 59, 60, 62, 63, -22, 36, 19, -25, 78,
	102, 68, -38, 102, -37, 84, -38, 82, 30, 55,
	-46, -57, -38, -54, -55, -38, -72, -52, 11, -25,
	-25, 56, 61, 56, 61, 56, 56, 56, -15, 36,
	102, 36, -38, 102, -38, 31, -42, 55, 55, -56,
	26, 27, -32, 12, 14, 66, 56, 56, -29, 64,
	94, 65, 7, -38, -55, -53, -33, -40, -33, 91,
	91, 91, -62, -57, 46, 46, 46, -58, 16, 34,
	-30, -71, -30, -30, 7, 21, 102, 55, 102, 102,
	-71, -71, -71,
}

var yyDef = [...]int16{
	40, -2, 1, 2, 42, 40, 3, 6, 7, 8,
	9, 10, 11, 12, 13, 14, 15, 16, 40, 40,
	40, 40, 40, 204, 195, 0, 0, 0, 209, 209,
	209, 41, 5, 0, 44, 46, 47, 48, 49, 0,
	0, 0, 0, 193, 0, 0, 205, 0, 0, 196,
	0, 191, 0, 191, 0, 37, 38, 39, 43, 4,
	19, 45, 0, 50, 0, 0, 82, 0, 24, 188,
	0, 151, 208, 0, 0, 0, 209, 208, 0, 209,
	0, 0, 0, 0, 0, 36, 18, 51, 53, 58,
	208, 56, 57, 92, 0, 0, 121, 122, 123, 0,
	151, 0, 137, 0, 0, 153, 0, 155, 156, 157,
	187, 140, 141, 142, 138, 139, 144, 176, 0, 0,
	90, 0, 0, 0, 209, 0, 206, 28, 0, 31,
	0, 33, 192, 0, 209, 40, 0, 54, 59, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 108, 109, 110,
	111, 112, 113, 114, 95, 0, 0, 0, 0, 119,
	132, 0, 0, 0, 106, 0, 0, 154, 0, 145,
	0, 0, 0, 90, 83, 162, 0, 189, 190, 152,
	25, 0, 194, 0, 0, 209, 202, 197, 198, 199,
	200, 201, 32, 34, 35, 0, 52, 60, 55, 93,
	94, 97, 98, 0, 116, 117, 0, 0, 0, 100,
	0, 104, 0, 124, 125, 126, 127, 128, 129, 130,
	131, 96, 118, 0, 186, 119, 133, 0, 0, 0,
	0, 149, 146, 0, 180, 0, 183, 180, 0, 178,
	162, 170, 0, 91, 209, 0, 207, 29, 0, 203,
	90, 61, 67, 0, 79, 81, 0, 99, 101, 0,
	0, 105, 120, 134, 0, 136, 0, 0, 147, 0,
	0, 20, 0, 182, 184, 21, 177, 0, 170, 23,
	0, 0, 26, 209, 30, 158, 0, 0, 70, 71,
	0, 0, 0, 0, 0, 40, 68, 0, 0, 0,
	115, 0, 102, 135, 0, 143, 150, 0, 0, 0,
	179, 22, 171, 163, 164, 167, 27, 160, 0, 62,
	65, 72, 0, 74, 0, 76, 77, 78, 84, 69,
	64, 80, 103, 107, 148, 0, 185, 0, 0, 166,
	168, 169, 162, 0, 0, 0, 73, 75, 63, 0,
	0, 0, 0, 172, 165, 170, 161, 159, 66, 0,
	0, 0, 181, 173, 0, 0, 0, 17, 0, 0,
	0, 88, 0, 0, 174, 0, 85, 0, 86, 87,
	0, 89, 175,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 103, 77, 70, 3,
	46, 102, 75, 73, 55, 74, 78, 76, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 101,
	48, 47, 49, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 72, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 71, 3, 50,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 51, 52, 53, 54, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
	68, 69, 79, 80, 81, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:167
		{
			SetParseTree(yylex, yyDollar[1].positionedStatements)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:173
		{
			yyVAL.positionedStatements = PositionedStatements{}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:177
		{
			yyVAL.positionedStatements = PositionedStatements{PositionStatement{Start: getStatementStart(yylex), End: GetCurrentPos(yylex), Statement: yyDollar[2].statement}}
		}
	case 4:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:181
		{
			yyVAL.positionedStatements = append(yyDollar[1].positionedStatements, PositionStatement{Start: getStatementStart(yylex), End: GetCurrentPos(yylex), Statement: yyDollar[4].statement})
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:185
		{
			yyVAL.positionedStatements = yyDollar[1].positionedStatements
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:191
		{
			yyVAL.statement = yyDollar[1].selStmt
		}
	case 17:
		yyDollar = yyS[yypt-13 : yypt+1]
//line sql.y:207
		{
			yyVAL.selStmt = &Select{Comments: Comments(yyDollar[2].bytes2), Distinct: yyDollar[3].str, SelectExprs: yyDollar[4].selectExprs, From: yyDollar[7].tableExprs, FromComments: Comments(yyDollar[6].bytes2), Where: NewWhere(AST_WHERE, yyDollar[8].boolExpr), GroupBy: GroupBy(yyDollar[9].valExprs), Having: NewWhere(AST_HAVING, yyDollar[10].boolExpr), OrderBy: yyDollar[11].orderBy, Limit: yyDollar[12].limit, Lock: yyDollar[13].str}
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:211
		{
			yyVAL.selStmt = &Select{Comments: Comments(yyDollar[2].bytes2), Distinct: yyDollar[3].str, SelectExprs: yyDollar[4].selectExprs}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:215
		{
			yyVAL.selStmt = &Union{Type: yyDollar[2].str, Left: yyDollar[1].selStmt, Right: yyDollar[3].selStmt}
		}
	case 20:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:221
		{
			yyVAL.statement = &Insert{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Columns: yyDollar[5].columns, Rows: yyDollar[6].insRows, OnDup: OnDup(yyDollar[7].updateExprs)}
		}
	case 21:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:225
		{
			cols := make(Columns, 0, len(yyDollar[6].updateExprs))
			vals := make(ValTuple, 0, len(yyDollar[6].updateExprs))
			for _, col := range yyDollar[6].updateExprs {
				cols = append(cols, &NonStarExpr{Expr: col.Name})
				vals = append(vals, col.Expr)
			}
			yyVAL.statement = &Insert{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Columns: cols, Rows: Values{vals}, OnDup: OnDup(yyDollar[7].updateExprs)}
		}
	case 22:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:237
		{
			yyVAL.statement = &Update{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[3].tableName, Exprs: yyDollar[5].updateExprs, Where: NewWhere(AST_WHERE, yyDollar[6].boolExpr), OrderBy: yyDollar[7].orderBy, Limit: yyDollar[8].limit}
		}
	case 23:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:243
		{
			yyVAL.statement = &Delete{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Where: NewWhere(AST_WHERE, yyDollar[5].boolExpr), OrderBy: yyDollar[6].orderBy, Limit: yyDollar[7].limit}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:249
		{
			yyVAL.statement = &Set{Comments: Comments(yyDollar[2].bytes2), Exprs: yyDollar[3].updateExprs}
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:255
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[4].bytes}
		}
	case 26:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:259
		{
			yyVAL.statement = &CreateTableAsSelect{Table: yyDollar[4].bytes, Select: yyDollar[6].selStmt}
		}
	case 27:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:263
		{
			// Change this to an alter statement
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[7].bytes, NewName: yyDollar[7].bytes}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:268
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[3].bytes}
		}
	case 29:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:274
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[4].bytes, NewName: yyDollar[4].bytes}
		}
	case 30:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:278
		{
			// Change this to a rename statement
			yyVAL.statement = &DDL{Action: AST_RENAME, Table: yyDollar[4].bytes, NewName: yyDollar[7].bytes}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:283
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[3].bytes, NewName: yyDollar[3].bytes}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:289
		{
			yyVAL.statement = &DDL{Action: AST_RENAME, Table: yyDollar[3].bytes, NewName: yyDollar[5].bytes}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:295
		{
			yyVAL.statement = &DDL{Action: AST_DROP, Table: yyDollar[4].bytes}
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:299
		{
			// Change this to an alter statement
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[5].bytes, NewName: yyDollar[5].bytes}
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:304
		{
			yyVAL.statement = &DDL{Action: AST_DROP, Table: yyDollar[4].bytes}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:310
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[3].bytes, NewName: yyDollar[3].bytes}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:316
		{
			yyVAL.statement = &Other{}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:320
		{
			yyVAL.statement = &Other{}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:324
		{
			yyVAL.statement = &Other{}
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:329
		{
			SetAllowComments(yylex, true)
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:333
		{
			yyVAL.bytes2 = yyDollar[2].bytes2
			SetAllowComments(yylex, false)
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:339
		{
			yyVAL.bytes2 = nil
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:343
		{
			yyVAL.bytes2 = append(yyDollar[1].bytes2, yyDollar[2].bytes)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:349
		{
			yyVAL.str = AST_UNION
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:353
		{
			yyVAL.str = AST_UNION_ALL
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:357
		{
			yyVAL.str = AST_SET_MINUS
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:361
		{
			yyVAL.str = AST_EXCEPT
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:365
		{
			yyVAL.str = AST_INTERSECT
		}
	case 49:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:370
		{
			yyVAL.str = ""
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:374
		{
			yyVAL.str = AST_DISTINCT
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:380
		{
			yyVAL.selectExprs = SelectExprs{yyDollar[1].selectExpr}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:384
		{
			yyVAL.selectExprs = append(yyVAL.selectExprs, yyDollar[3].selectExpr)
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:390
		{
			yyVAL.selectExpr = &StarExpr{}
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:394
		{
			yyVAL.selectExpr = &NonStarExpr{Expr: yyDollar[1].expr, As: yyDollar[2].bytes}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:398
		{
			yyVAL.selectExpr = &StarExpr{TableName: yyDollar[1].bytes}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:404
		{
			yyVAL.expr = yyDollar[1].boolExpr
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:408
		{
			yyVAL.expr = yyDollar[1].valExpr
		}
	case 58:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:413
		{
			yyVAL.bytes = nil
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:417
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:421
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:427
		{
			yyVAL.tableExprs = TableExprs{yyDollar[1].tableExpr}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:431
		{
			yyVAL.tableExprs = append(yyVAL.tableExprs, yyDollar[3].tableExpr)
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:437
		{
			yyVAL.tableExpr = &AliasedTableExpr{Position: GetCurrentPos(yylex), Expr: yyDollar[1].smTableExpr, As: yyDollar[2].bytes, Hints: yyDollar[4].indexHints}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:441
		{
			yyVAL.tableExpr = &ParenTableExpr{Expr: yyDollar[2].tableExpr}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:445
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr}
		}
	case 66:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:449
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr, On: yyDollar[5].boolExpr}
		}
	case 67:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:454
		{
			yyVAL.bytes = nil
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:458
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:462
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:468
		{
			yyVAL.str = AST_JOIN
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:472
		{
			yyVAL.str = AST_STRAIGHT_JOIN
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:476
		{
			yyVAL.str = AST_LEFT_JOIN
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:480
		{
			yyVAL.str = AST_LEFT_JOIN
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:484
		{
			yyVAL.str = AST_RIGHT_JOIN
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:488
		{
			yyVAL.str = AST_RIGHT_JOIN
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:492
		{
			yyVAL.str = AST_JOIN
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:496
		{
			yyVAL.str = AST_CROSS_JOIN
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:500
		{
			yyVAL.str = AST_NATURAL_JOIN
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:506
		{
			yyVAL.smTableExpr = &TableName{Name: yyDollar[1].bytes}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:510
		{
			yyVAL.smTableExpr = &TableName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:514
		{
			yyVAL.smTableExpr = yyDollar[1].subquery
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:520
		{
			yyVAL.tableName = &TableName{Name: yyDollar[1].bytes}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:524
		{
			yyVAL.tableName = &TableName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 84:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:529
		{
			yyVAL.indexHints = nil
		}
	case 85:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:533
		{
			yyVAL.indexHints = &IndexHints{Type: AST_USE, Indexes: yyDollar[4].bytes2}
		}
	case 86:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:537
		{
			yyVAL.indexHints = &IndexHints{Type: AST_IGNORE, Indexes: yyDollar[4].bytes2}
		}
	case 87:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:541
		{
			yyVAL.indexHints = &IndexHints{Type: AST_FORCE, Indexes: yyDollar[4].bytes2}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:547
		{
			yyVAL.bytes2 = [][]byte{yyDollar[1].bytes}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:551
		{
			yyVAL.bytes2 = append(yyDollar[1].bytes2, yyDollar[3].bytes)
		}
	case 90:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:556
		{
			yyVAL.boolExpr = nil
		}
	case 91:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:560
		{
			yyVAL.boolExpr = yyDollar[2].boolExpr
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:567
		{
			yyVAL.boolExpr = &AndExpr{Left: yyDollar[1].boolExpr, Right: yyDollar[3].boolExpr}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:571
		{
			yyVAL.boolExpr = &OrExpr{Left: yyDollar[1].boolExpr, Right: yyDollar[3].boolExpr}
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:575
		{
			yyVAL.boolExpr = &NotExpr{Expr: yyDollar[2].boolExpr}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:579
		{
			yyVAL.boolExpr = &ParenBoolExpr{Expr: yyDollar[2].boolExpr}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:585
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: yyDollar[2].str, Right: yyDollar[3].valExpr}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:589
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_IN, Right: yyDollar[3].colTuple}
		}
	case 99:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:593
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_NOT_IN, Right: yyDollar[4].colTuple}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:597
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_LIKE, Right: yyDollar[3].valExpr}
		}
	case 101:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:601
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_NOT_LIKE, Right: yyDollar[4].valExpr}
		}
	case 102:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:605
		{
			yyVAL.boolExpr = &RangeCond{Left: yyDollar[1].valExpr, Operator: AST_BETWEEN, From: yyDollar[3].valExpr, To: yyDollar[5].valExpr}
		}
	case 103:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:609
		{
			yyVAL.boolExpr = &RangeCond{Left: yyDollar[1].valExpr, Operator: AST_NOT_BETWEEN, From: yyDollar[4].valExpr, To: yyDollar[6].valExpr}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:613
		{
			yyVAL.boolExpr = &NullCheck{Operator: AST_IS_NULL, Expr: yyDollar[1].valExpr}
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:617
		{
			yyVAL.boolExpr = &NullCheck{Operator: AST_IS_NOT_NULL, Expr: yyDollar[1].valExpr}
		}
	case 106:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:621
		{
			yyVAL.boolExpr = &ExistsExpr{Subquery: yyDollar[2].subquery}
		}
	case 107:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:625
		{
			yyVAL.boolExpr = &KeyrangeExpr{Start: yyDollar[3].valExpr, End: yyDollar[5].valExpr}
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:631
		{
			yyVAL.str = AST_EQ
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:635
		{
			yyVAL.str = AST_LT
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:639
		{
			yyVAL.str = AST_GT
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:643
		{
			yyVAL.str = AST_LE
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:647
		{
			yyVAL.str = AST_GE
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:651
		{
			yyVAL.str = AST_NE
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:655
		{
			yyVAL.str = AST_NSE
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:661
		{
			yyVAL.colTuple = ValTuple(yyDollar[2].valExprs)
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:665
		{
			yyVAL.colTuple = yyDollar[1].subquery
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:669
		{
			yyVAL.colTuple = ListArg(yyDollar[1].bytes)
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:675
		{
			yyVAL.subquery = &Subquery{yyDollar[2].selStmt}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:681
		{
			yyVAL.valExprs = ValExprs{yyDollar[1].valExpr}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:685
		{
			yyVAL.valExprs = append(yyDollar[1].valExprs, yyDollar[3].valExpr)
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:691
		{
			yyVAL.valExpr = yyDollar[1].valExpr
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:695
		{
			yyVAL.valExpr = yyDollar[1].colName
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:699
		{
			yyVAL.valExpr = yyDollar[1].rowTuple
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:703
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITAND, Right: yyDollar[3].valExpr}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:707
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITOR, Right: yyDollar[3].valExpr}
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:711
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITXOR, Right: yyDollar[3].valExpr}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:715
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_PLUS, Right: yyDollar[3].valExpr}
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:719
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MINUS, Right: yyDollar[3].valExpr}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:723
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MULT, Right: yyDollar[3].valExpr}
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:727
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_DIV, Right: yyDollar[3].valExpr}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:731
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MOD, Right: yyDollar[3].valExpr}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:735
		{
			if num, ok := yyDollar[2].valExpr.(NumVal); ok {
				switch yyDollar[1].byt {
				case '-':
					yyVAL.valExpr = append(NumVal("-"), num...)
				case '+':
					yyVAL.valExpr = num
				default:
					yyVAL.valExpr = &UnaryExpr{Operator: yyDollar[1].byt, Expr: yyDollar[2].valExpr}
				}
			} else {
				yyVAL.valExpr = &UnaryExpr{Operator: yyDollar[1].byt, Expr: yyDollar[2].valExpr}
			}
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:750
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes}
		}
	case 134:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:754
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 135:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:758
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Distinct: true, Exprs: yyDollar[4].selectExprs}
		}
	case 136:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:762
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:766
		{
			yyVAL.valExpr = yyDollar[1].caseExpr
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:772
		{
			yyVAL.bytes = IF_BYTES
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:776
		{
			yyVAL.bytes = VALUES_BYTES
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:782
		{
			yyVAL.byt = AST_UPLUS
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:786
		{
			yyVAL.byt = AST_UMINUS
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:790
		{
			yyVAL.byt = AST_TILDA
		}
	case 143:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:796
		{
			yyVAL.caseExpr = &CaseExpr{Expr: yyDollar[2].valExpr, Whens: yyDollar[3].whens, Else: yyDollar[4].valExpr}
		}
	case 144:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:801
		{
			yyVAL.valExpr = nil
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:805
		{
			yyVAL.valExpr = yyDollar[1].valExpr
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:811
		{
			yyVAL.whens = []*When{yyDollar[1].when}
		}
	case 147:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:815
		{
			yyVAL.whens = append(yyDollar[1].whens, yyDollar[2].when)
		}
	case 148:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:821
		{
			yyVAL.when = &When{Cond: yyDollar[2].boolExpr, Val: yyDollar[4].valExpr}
		}
	case 149:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:826
		{
			yyVAL.valExpr = nil
		}
	case 150:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:830
		{
			yyVAL.valExpr = yyDollar[2].valExpr
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:836
		{
			yyVAL.colName = &ColName{Name: yyDollar[1].bytes}
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:840
		{
			yyVAL.colName = &ColName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:846
		{
			yyVAL.valExpr = StrVal(yyDollar[1].bytes)
		}
	case 154:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:850
		{
			yyVAL.valExpr = ValArg(":v$" + string(yyDollar[2].bytes))
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:854
		{
			yyVAL.valExpr = NumVal(yyDollar[1].bytes)
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:858
		{
			yyVAL.valExpr = ValArg(yyDollar[1].bytes)
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:862
		{
			yyVAL.valExpr = &NullVal{}
		}
	case 158:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:867
		{
			yyVAL.valExprs = nil
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:871
		{
			yyVAL.valExprs = yyDollar[3].valExprs
		}
	case 160:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:876
		{
			yyVAL.boolExpr = nil
		}
	case 161:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:880
		{
			yyVAL.boolExpr = yyDollar[2].boolExpr
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:885
		{
			yyVAL.orderBy = nil
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:889
		{
			yyVAL.orderBy = yyDollar[3].orderBy
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:895
		{
			yyVAL.orderBy = OrderBy{yyDollar[1].order}
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:899
		{
			yyVAL.orderBy = append(yyDollar[1].orderBy, yyDollar[3].order)
		}
	case 166:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:905
		{
			yyVAL.order = &Order{Expr: yyDollar[1].valExpr, Direction: yyDollar[2].str}
		}
	case 167:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:910
		{
			yyVAL.str = AST_ASC
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:914
		{
			yyVAL.str = AST_ASC
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:918
		{
			yyVAL.str = AST_DESC
		}
	case 170:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:923
		{
			yyVAL.limit = nil
		}
	case 171:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:927
		{
			yyVAL.limit = &Limit{Rowcount: yyDollar[2].valExpr}
		}
	case 172:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:931
		{
			yyVAL.limit = &Limit{Offset: yyDollar[2].valExpr, Rowcount: yyDollar[4].valExpr}
		}
	case 173:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:936
		{
			yyVAL.str = ""
		}
	case 174:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:940
		{
			yyVAL.str = AST_FOR_UPDATE
		}
	case 175:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:944
		{
			if !bytes.Equal(yyDollar[3].bytes, SHARE) {
				yylex.Error("expecting share")
				return 1
			}
			if !bytes.Equal(yyDollar[4].bytes, MODE) {
				yylex.Error("expecting mode")
				return 1
			}
			yyVAL.str = AST_SHARE_MODE
		}
	case 176:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:957
		{
			yyVAL.columns = nil
		}
	case 177:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:961
		{
			yyVAL.columns = yyDollar[2].columns
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:967
		{
			yyVAL.columns = Columns{&NonStarExpr{Expr: yyDollar[1].colName}}
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:971
		{
			yyVAL.columns = append(yyVAL.columns, &NonStarExpr{Expr: yyDollar[3].colName})
		}
	case 180:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:976
		{
			yyVAL.updateExprs = nil
		}
	case 181:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:980
		{
			yyVAL.updateExprs = yyDollar[5].updateExprs
		}
	case 182:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:986
		{
			yyVAL.insRows = yyDollar[2].values
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:990
		{
			yyVAL.insRows = yyDollar[1].selStmt
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:996
		{
			yyVAL.values = Values{yyDollar[1].rowTuple}
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1000
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].rowTuple)
		}
	case 186:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1006
		{
			yyVAL.rowTuple = ValTuple(yyDollar[2].valExprs)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1010
		{
			yyVAL.rowTuple = yyDollar[1].subquery
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1016
		{
			yyVAL.updateExprs = UpdateExprs{yyDollar[1].updateExpr}
		}
	case 189:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1020
		{
			yyVAL.updateExprs = append(yyDollar[1].updateExprs, yyDollar[3].updateExpr)
		}
	case 190:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1026
		{
			yyVAL.updateExpr = &UpdateExpr{Name: yyDollar[1].colName, Expr: yyDollar[3].valExpr}
		}
	case 191:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1031
		{
			yyVAL.empty = struct{}{}
		}
	case 192:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1033
		{
			yyVAL.empty = struct{}{}
		}
	case 193:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1036
		{
			yyVAL.empty = struct{}{}
		}
	case 194:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1038
		{
			yyVAL.empty = struct{}{}
		}
	case 195:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1041
		{
			yyVAL.empty = struct{}{}
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1043
		{
			yyVAL.empty = struct{}{}
		}
	case 197:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1047
		{
			yyVAL.empty = struct{}{}
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1049
		{
			yyVAL.empty = struct{}{}
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1051
		{
			yyVAL.empty = struct{}{}
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1053
		{
			yyVAL.empty = struct{}{}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1055
		{
			yyVAL.empty = struct{}{}
		}
	case 202:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1058
		{
			yyVAL.empty = struct{}{}
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1060
		{
			yyVAL.empty = struct{}{}
		}
	case 204:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1063
		{
			yyVAL.empty = struct{}{}
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1065
		{
			yyVAL.empty = struct{}{}
		}
	case 206:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1068
		{
			yyVAL.empty = struct{}{}
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1070
		{
			yyVAL.empty = struct{}{}
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1074
		{
			yyVAL.bytes = bytes.ToLower(yyDollar[1].bytes)
		}
	case 209:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1079
		{
			ForceEOF(yylex)
		}
	}
	goto yystack /* stack new state and value */
}
