// Code generated by goyacc -o sql.go sql.y. DO NOT EDIT.

//line sql.y:6
package sqlparser

import __yyfmt__ "fmt"

//line sql.y:6

import (
	"bytes"
)

func SetParseTree(yylex interface{}, stmt Statement) {
	yylex.(*Tokenizer).ParseTree = stmt
}

func getStatementStart(yylex interface{}) int {
	return yylex.(*Tokenizer).GetAndPopStatementStart()
}

func SetAllowComments(yylex interface{}, allow bool) {
	yylex.(*Tokenizer).AllowComments = allow
}

func GetCurrentPos(yylex interface{}) int {
	return yylex.(*Tokenizer).Position
}

func ForceEOF(yylex interface{}) {
	yylex.(*Tokenizer).ForceEOF = true
}

var (
	SHARE        = []byte("share")
	MODE         = []byte("mode")
	IF_BYTES     = []byte("if")
	VALUES_BYTES = []byte("values")
)

//line sql.y:43
type yySymType struct {
	yys                  int
	empty                struct{}
	statement            Statement
	statements           Statements
	selStmt              SelectStatement
	byt                  byte
	bytes                []byte
	bytes2               [][]byte
	str                  string
	selectExprs          SelectExprs
	selectExpr           SelectExpr
	columns              Columns
	colName              *ColName
	tableExprs           TableExprs
	tableExpr            TableExpr
	smTableExpr          SimpleTableExpr
	tableName            *TableName
	indexHints           *IndexHints
	expr                 Expr
	boolExpr             BoolExpr
	valExpr              ValExpr
	colTuple             ColTuple
	valExprs             ValExprs
	values               Values
	rowTuple             RowTuple
	subquery             *Subquery
	caseExpr             *CaseExpr
	whens                []*When
	when                 *When
	orderBy              OrderBy
	order                *Order
	limit                *Limit
	insRows              InsertRows
	updateExprs          UpdateExprs
	updateExpr           *UpdateExpr
	position             int
	positionedStatements PositionedStatements
	withCTE              *WithCTE
	withList             []*WithCTE
}

const LEX_ERROR = 57346
const SELECT = 57347
const INSERT = 57348
const UPDATE = 57349
const DELETE = 57350
const FROM = 57351
const WHERE = 57352
const GROUP = 57353
const HAVING = 57354
const ORDER = 57355
const BY = 57356
const LIMIT = 57357
const FOR = 57358
const ALL = 57359
const DISTINCT = 57360
const AS = 57361
const EXISTS = 57362
const IN = 57363
const IS = 57364
const LIKE = 57365
const BETWEEN = 57366
const NULL = 57367
const ASC = 57368
const DESC = 57369
const VALUES = 57370
const INTO = 57371
const DUPLICATE = 57372
const KEY = 57373
const DEFAULT = 57374
const SET = 57375
const LOCK = 57376
const KEYRANGE = 57377
const ID = 57378
const STRING = 57379
const NUMBER = 57380
const VALUE_ARG = 57381
const LIST_ARG = 57382
const COMMENT = 57383
const LE = 57384
const GE = 57385
const NE = 57386
const NULL_SAFE_EQUAL = 57387
const UNION = 57388
const MINUS = 57389
const EXCEPT = 57390
const INTERSECT = 57391
const JOIN = 57392
const STRAIGHT_JOIN = 57393
const LEFT = 57394
const RIGHT = 57395
const INNER = 57396
const OUTER = 57397
const CROSS = 57398
const NATURAL = 57399
const USE = 57400
const FORCE = 57401
const ON = 57402
const OR = 57403
const AND = 57404
const NOT = 57405
const CONCAT = 57406
const JSON_EXTRACT = 57407
const JSON_EXTRACT_TEXT = 57408
const UNARY = 57409
const CAST = 57410
const CASE = 57411
const WHEN = 57412
const THEN = 57413
const ELSE = 57414
const END = 57415
const CREATE = 57416
const ALTER = 57417
const DROP = 57418
const RENAME = 57419
const ANALYZE = 57420
const TEMPORARY = 57421
const TEMP = 57422
const TABLE = 57423
const INDEX = 57424
const VIEW = 57425
const TO = 57426
const IGNORE = 57427
const IF = 57428
const UNIQUE = 57429
const USING = 57430
const ADD = 57431
const COLUMN = 57432
const BEGIN = 57433
const COMMIT = 57434
const WITH = 57435
const SHOW = 57436
const DESCRIBE = 57437
const EXPLAIN = 57438

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"SELECT",
	"INSERT",
	"UPDATE",
	"DELETE",
	"FROM",
	"WHERE",
	"GROUP",
	"HAVING",
	"ORDER",
	"BY",
	"LIMIT",
	"FOR",
	"ALL",
	"DISTINCT",
	"AS",
	"EXISTS",
	"IN",
	"IS",
	"LIKE",
	"BETWEEN",
	"NULL",
	"ASC",
	"DESC",
	"VALUES",
	"INTO",
	"DUPLICATE",
	"KEY",
	"DEFAULT",
	"SET",
	"LOCK",
	"KEYRANGE",
	"ID",
	"STRING",
	"NUMBER",
	"VALUE_ARG",
	"LIST_ARG",
	"COMMENT",
	"LE",
	"GE",
	"NE",
	"NULL_SAFE_EQUAL",
	"'('",
	"'='",
	"'<'",
	"'>'",
	"'~'",
	"UNION",
	"MINUS",
	"EXCEPT",
	"INTERSECT",
	"','",
	"JOIN",
	"STRAIGHT_JOIN",
	"LEFT",
	"RIGHT",
	"INNER",
	"OUTER",
	"CROSS",
	"NATURAL",
	"USE",
	"FORCE",
	"ON",
	"OR",
	"AND",
	"NOT",
	"'&'",
	"'|'",
	"'^'",
	"CONCAT",
	"JSON_EXTRACT",
	"JSON_EXTRACT_TEXT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'.'",
	"UNARY",
	"CAST",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"CREATE",
	"ALTER",
	"DROP",
	"RENAME",
	"ANALYZE",
	"TEMPORARY",
	"TEMP",
	"TABLE",
	"INDEX",
	"VIEW",
	"TO",
	"IGNORE",
	"IF",
	"UNIQUE",
	"USING",
	"ADD",
	"COLUMN",
	"BEGIN",
	"COMMIT",
	"WITH",
	"SHOW",
	"DESCRIBE",
	"EXPLAIN",
	"';'",
	"')'",
	"'$'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 795

var yyAct = [...]int16{
	117, 282, 447, 109, 81, 375, 108, 333, 285, 192,
	115, 303, 325, 114, 113, 210, 103, 288, 242, 276,
	82, 401, 454, 400, 128, 163, 162, 104, 5, 222,
	87, 97, 299, 19, 127, 301, 191, 133, 454, 150,
	7, 454, 436, 435, 3, 85, 123, 125, 126, 84,
	35, 331, 434, 90, 91, 195, 19, 94, 416, 131,
	93, 98, 83, 331, 44, 45, 46, 47, 48, 127,
	89, 264, 7, 70, 157, 157, 127, 88, 72, 133,
	456, 123, 125, 126, 62, 129, 130, 85, 123, 125,
	126, 146, 119, 134, 58, 417, 455, 195, 266, 453,
	154, 131, 19, 19, 300, 331, 365, 159, 277, 446,
	132, 37, 38, 39, 40, 189, 193, 161, 188, 190,
	194, 428, 56, 124, 57, 143, 279, 129, 130, 157,
	157, 266, 424, 362, 119, 134, 18, 84, 204, 155,
	84, 208, 214, 290, 213, 141, 199, 277, 137, 322,
	83, 162, 132, 83, 19, 19, 359, 326, 124, 18,
	212, 237, 214, 330, 419, 124, 189, 189, 241, 239,
	240, 249, 250, 377, 253, 254, 255, 256, 257, 258,
	259, 260, 261, 262, 263, 236, 306, 317, 315, 267,
	244, 346, 347, 348, 349, 350, 305, 351, 352, 268,
	295, 235, 273, 358, 73, 18, 18, 84, 84, 86,
	153, 281, 63, 270, 272, 189, 274, 215, 287, 418,
	83, 283, 92, 296, 284, 37, 38, 39, 40, 37,
	38, 39, 40, 50, 51, 49, 393, 53, 357, 421,
	423, 54, 280, 64, 65, 66, 67, 268, 396, 163,
	162, 310, 311, 308, 289, 78, 139, 18, 18, 392,
	307, 59, 60, 61, 238, 309, 391, 42, 367, 251,
	314, 244, 178, 179, 180, 422, 176, 177, 178, 179,
	180, 324, 163, 162, 323, 139, 266, 265, 316, 156,
	328, 234, 389, 332, 329, 321, 326, 390, 144, 145,
	19, 20, 21, 22, 147, 140, 387, 149, 407, 211,
	338, 388, 339, 252, 96, 370, 361, 356, 343, 174,
	175, 176, 177, 178, 179, 180, 366, 337, 23, 289,
	307, 289, 84, 135, 364, 157, 138, 319, 373, 376,
	372, 101, 442, 441, 211, 371, 173, 174, 175, 176,
	177, 178, 179, 180, 344, 216, 385, 386, 306, 346,
	347, 348, 349, 350, 399, 351, 352, 233, 305, 307,
	307, 402, 403, 440, 433, 398, 99, 37, 38, 39,
	40, 405, 84, 412, 24, 25, 27, 26, 28, 139,
	245, 195, 381, 201, 206, 283, 243, 200, 394, 198,
	197, 29, 30, 18, 31, 32, 33, 207, 228, 196,
	426, 376, 102, 427, 68, 202, 92, 85, 189, 268,
	189, 430, 429, 432, 397, 431, 84, 226, 395, 355,
	437, 230, 291, 293, 84, 439, 297, 438, 382, 83,
	363, 448, 448, 448, 449, 450, 354, 283, 160, 271,
	342, 121, 215, 457, 341, 458, 127, 92, 459, 133,
	340, 232, 231, 220, 219, 92, 122, 107, 123, 125,
	126, 209, 151, 148, 142, 79, 43, 112, 100, 95,
	444, 131, 6, 136, 404, 225, 227, 224, 369, 77,
	246, 313, 247, 248, 452, 218, 19, 152, 445, 229,
	111, 336, 294, 292, 217, 74, 76, 129, 130, 105,
	71, 121, 334, 415, 119, 134, 127, 335, 69, 133,
	286, 414, 80, 384, 211, 451, 122, 85, 123, 125,
	126, 121, 132, 425, 4, 41, 127, 112, 380, 133,
	221, 131, 52, 298, 269, 124, 122, 107, 123, 125,
	126, 378, 379, 223, 55, 205, 443, 112, 408, 374,
	111, 131, 383, 320, 203, 275, 120, 129, 130, 116,
	118, 327, 278, 164, 119, 134, 110, 413, 420, 304,
	111, 345, 302, 106, 353, 158, 75, 129, 130, 105,
	36, 34, 132, 411, 119, 134, 17, 16, 121, 18,
	15, 14, 13, 127, 12, 124, 133, 11, 10, 9,
	8, 2, 132, 122, 85, 123, 125, 126, 165, 169,
	167, 168, 1, 0, 112, 124, 0, 0, 131, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 184,
	185, 186, 187, 0, 181, 182, 183, 111, 0, 409,
	410, 0, 0, 0, 129, 130, 0, 0, 0, 0,
	0, 119, 134, 0, 0, 0, 166, 170, 171, 172,
	173, 174, 175, 176, 177, 178, 179, 180, 0, 132,
	0, 0, 0, 368, 165, 169, 167, 168, 0, 0,
	0, 0, 124, 170, 171, 172, 173, 174, 175, 176,
	177, 178, 179, 180, 406, 184, 185, 186, 187, 318,
	181, 182, 183, 0, 0, 0, 0, 0, 0, 170,
	171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
	0, 0, 166, 170, 171, 172, 173, 174, 175, 176,
	177, 178, 179, 180, 360, 0, 170, 171, 172, 173,
	174, 175, 176, 177, 178, 179, 180, 0, 0, 0,
	170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
	180, 312, 0, 170, 171, 172, 173, 174, 175, 176,
	177, 178, 179, 180, 170, 171, 172, 173, 174, 175,
	176, 177, 178, 179, 180,
}

var yyPact = [...]int16{
	-1000, -1000, -84, 295, -1000, -1000, -1000, 326, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 440, -1000,
	-1000, -1000, -1000, -1000, 139, 24, -2, 165, -12, -1000,
	-1000, -1000, -1000, -1000, 373, 295, 28, 493, -1000, -1000,
	-1000, 149, -1000, 486, 488, 460, 439, 513, 381, -71,
	-19, -26, -44, 380, -1000, -36, 380, -1000, 443, -70,
	380, -70, 442, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 326, 440, 366, 511, -1000, 439, 450, 67,
	439, 201, -1000, 258, -1000, 64, 438, 56, -71, -71,
	380, -1000, -1000, 437, -1000, -60, 436, 477, 144, 380,
	-1000, -1000, 28, 280, -1000, -1000, 429, 36, 215, 663,
	-1000, 578, 491, -1000, -1000, -1000, 9, 363, 354, 353,
	-1000, 351, 347, -1000, 377, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 9, 361, 381, 435, 514, 381,
	9, 421, 485, 475, 428, 427, -74, -1000, 395, -1000,
	426, -1000, -1000, 425, -1000, 178, -1000, 511, -1000, -1000,
	380, 186, 578, 578, 9, 350, 469, 9, 9, 244,
	9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	9, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 663,
	-42, 174, 76, 663, -1000, 51, 431, 511, 9, -1000,
	28, 44, -1000, 23, 714, 98, 381, 381, 334, -1000,
	507, 578, -1000, 714, -1000, -1000, -1000, 97, -1000, 484,
	483, 134, 380, -1000, -67, -1000, -1000, -1000, -1000, -1,
	-1000, -1000, -1000, -1000, -1000, 322, -1000, -1000, -1000, -1000,
	83, 714, -1000, 51, -1000, -1000, 350, 9, 9, 714,
	703, -1000, 466, 273, 273, 273, 245, 200, 200, 194,
	194, -1000, -1000, -1000, -1000, -1000, 9, -1000, 714, -1000,
	75, 511, 74, 690, 282, 62, -1000, 578, 91, 345,
	326, 230, 50, -1000, 507, 497, 503, 215, -1000, 326,
	28, -1000, 97, -1000, 97, 424, -1000, -1000, 418, -1000,
	414, -1000, 299, 303, 410, 150, 157, -1000, 43, -1000,
	714, 676, 9, -1000, 714, -1000, 20, -1000, 404, 44,
	18, -1000, 9, 182, 597, -1000, 458, 260, -1000, -1000,
	-1000, 381, 497, -1000, 9, 9, -1000, 60, -1000, -1000,
	346, -1000, 402, 512, 322, 322, -1000, -1000, 250, 236,
	210, 203, 180, -1000, -1000, 392, 135, 388, 511, -1000,
	9, 714, -1000, -90, -92, -1000, 714, 9, 9, 453,
	345, -1000, -1000, 649, 253, -1000, 623, -1000, -1000, -1000,
	-1000, 381, -1000, 509, 499, 303, -8, -1000, 163, -1000,
	108, -1000, -1000, -1000, 175, -1000, -1000, -1000, 19, 714,
	-1000, -1000, 714, 714, 526, -1000, 9, 9, -1000, -1000,
	-1000, -1000, 8, 507, 578, 9, 578, 328, -1000, -1000,
	-1000, -45, -54, -55, -1000, 381, 714, -1000, -1000, 497,
	215, 231, 215, 381, 327, 297, 296, 201, 464, -4,
	380, 380, 380, -1000, 518, 473, -1000, -14, -1000, -17,
	-33, -1000, 380, -1000, 380, -1000, -1000, 380, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 622, 482, 611, 36, 17, 610, 609, 608, 607,
	604, 602, 601, 600, 597, 596, 44, 591, 590, 586,
	16, 27, 585, 584, 583, 582, 11, 581, 579, 255,
	578, 2, 15, 577, 6, 576, 573, 572, 14, 3,
	18, 9, 571, 10, 570, 24, 569, 13, 566, 565,
	19, 564, 563, 562, 8, 559, 5, 558, 7, 556,
	555, 1, 12, 4, 20, 314, 209, 554, 553, 543,
	542, 540, 538, 0, 212, 267, 535, 534,
}

var yyR1 = [...]int8{
	0, 1, 3, 3, 3, 3, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 4, 4, 4,
	4, 5, 5, 76, 76, 75, 6, 6, 7, 8,
	9, 10, 10, 10, 10, 10, 10, 10, 10, 11,
	11, 11, 12, 13, 13, 13, 14, 15, 15, 15,
	15, 15, 77, 16, 17, 17, 18, 18, 18, 18,
	18, 19, 19, 20, 20, 21, 21, 21, 24, 24,
	22, 22, 22, 25, 25, 26, 26, 26, 26, 26,
	23, 23, 23, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 28, 28, 28, 28, 29, 29, 30, 30,
	30, 30, 31, 31, 32, 32, 34, 34, 34, 34,
	34, 35, 35, 35, 35, 35, 35, 35, 35, 35,
	35, 35, 36, 36, 36, 36, 36, 36, 36, 40,
	40, 40, 45, 41, 41, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 44, 44, 46, 46,
	46, 48, 51, 51, 49, 49, 50, 50, 52, 52,
	47, 47, 47, 38, 38, 38, 38, 38, 53, 53,
	33, 33, 54, 54, 55, 55, 56, 57, 57, 57,
	58, 58, 58, 59, 59, 59, 60, 60, 61, 61,
	62, 62, 37, 37, 42, 42, 43, 43, 63, 63,
	64, 65, 65, 66, 66, 67, 67, 68, 68, 68,
	68, 68, 68, 68, 69, 69, 70, 70, 71, 71,
	72, 72, 73, 74,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 4, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 3, 13, 4,
	3, 1, 3, 1, 3, 5, 7, 7, 8, 7,
	3, 5, 6, 6, 7, 8, 8, 9, 4, 6,
	7, 4, 5, 4, 5, 5, 3, 2, 2, 2,
	2, 2, 0, 2, 0, 2, 1, 2, 1, 1,
	1, 0, 1, 1, 3, 1, 2, 3, 1, 1,
	0, 1, 2, 1, 3, 4, 3, 3, 5, 7,
	0, 1, 2, 1, 1, 2, 3, 2, 3, 2,
	2, 2, 1, 3, 4, 1, 1, 3, 0, 5,
	5, 5, 1, 3, 0, 2, 1, 3, 3, 2,
	3, 3, 3, 4, 3, 4, 5, 6, 3, 4,
	2, 6, 1, 1, 1, 1, 1, 1, 1, 3,
	1, 1, 3, 1, 3, 1, 1, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	3, 4, 5, 4, 6, 1, 1, 1, 1, 1,
	1, 5, 0, 1, 1, 2, 4, 4, 0, 2,
	1, 3, 3, 1, 2, 1, 1, 1, 0, 3,
	0, 2, 0, 3, 1, 3, 2, 0, 1, 1,
	0, 2, 4, 0, 2, 4, 0, 3, 1, 3,
	0, 5, 2, 1, 1, 3, 3, 1, 1, 3,
	3, 0, 2, 0, 3, 0, 1, 1, 1, 1,
	1, 4, 2, 1, 0, 1, 0, 1, 0, 2,
	0, 3, 1, 0,
}

var yyChk = [...]int16{
	-1000, -1, -3, -16, -77, 112, -2, -4, -6, -7,
	-8, -9, -10, -11, -12, -13, -14, -15, 108, 5,
	6, 7, 8, 33, 89, 90, 92, 91, 93, 106,
	107, 109, 110, 111, -17, -16, -18, 51, 52, 53,
	54, -76, -75, 36, -16, -16, -16, -16, -16, 96,
	94, 95, -70, 98, 102, -67, 98, 100, 96, 96,
	97, 98, 96, -74, -74, -74, -74, -74, 41, -2,
	-4, 17, -4, 55, 19, -19, 18, 29, -29, 36,
	9, -63, -64, -47, -73, 36, -66, 101, 96, 96,
	97, -73, 36, 96, -73, 36, -65, 101, -73, -65,
	36, -75, 46, -20, -21, 78, -24, 36, -34, -39,
	-35, 69, 46, -38, -47, -43, -46, -73, -44, 83,
	-48, 20, 35, 37, 114, 38, 39, 25, -45, 76,
	77, 50, 101, 28, 84, -29, 33, 81, -29, 55,
	47, 81, 36, 69, -66, -66, -73, -74, 36, -74,
	99, 36, 20, 66, -73, -4, 9, 55, -22, -73,
	19, 81, 68, 67, -36, 21, 69, 23, 24, 22,
	70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
	80, 47, 48, 49, 42, 43, 44, 45, -34, -39,
	-34, -4, -41, -39, -39, 46, 46, 46, 46, -45,
	46, 46, 38, -51, -39, -60, 33, 46, -63, 36,
	-32, 10, -64, -39, -73, 31, -74, 19, 20, 36,
	36, -71, 103, -68, 92, 90, 32, 91, 13, 104,
	36, 36, 36, -74, 113, -16, -21, -73, 78, -34,
	-34, -39, -40, 46, -45, 40, 21, 23, 24, -39,
	-39, 25, 69, -39, -39, -39, -39, -39, -39, -39,
	-39, -39, -39, -39, 113, 113, 55, 113, -39, 113,
	-20, 18, -20, -39, -38, -49, -50, 85, -37, 28,
	-4, -63, -61, -47, -32, -54, 13, -34, -5, -4,
	46, -74, 19, -74, 19, 66, -73, -74, -69, 99,
	105, 36, -25, -26, -28, 46, 36, -45, -41, -40,
	-39, -39, 68, 25, -39, 113, -20, 113, 19, 55,
	-52, -50, 87, -34, -39, -62, 66, -42, -43, -62,
	113, 55, -54, -58, 15, 14, -74, -4, -5, -5,
	36, 36, 36, -32, 55, -27, 56, 57, 58, 59,
	60, 62, 63, -23, 36, 19, -26, 81, 46, 113,
	68, -39, 113, 36, -38, 88, -39, 86, 86, 30,
	55, -47, -58, -39, -55, -56, -39, 113, -74, -74,
	-72, 46, 36, -53, 11, -26, -26, 56, 61, 56,
	61, 56, 56, 56, -16, 36, 113, 36, -20, -39,
	113, 113, -39, -39, 31, -43, 55, 55, -57, 26,
	27, -74, -61, -33, 12, 14, 66, 103, 56, 56,
	-30, 64, 100, 65, 113, 7, -39, -56, 113, -54,
	-34, -41, -34, 46, 97, 97, 97, -63, -58, -61,
	46, 46, 46, -59, 16, 34, 113, -31, -73, -31,
	-31, 7, 21, 113, 55, 113, 113, -73, -73, -73,
}

var yyDef = [...]int16{
	52, -2, 1, 2, 54, 52, 3, 6, 7, 8,
	9, 10, 11, 12, 13, 14, 15, 16, 0, 52,
	52, 52, 52, 52, 226, 215, 0, 0, 0, 233,
	233, 233, 233, 233, 53, 5, 0, 56, 58, 59,
	60, 0, 23, 0, 61, 0, 0, 0, 0, 213,
	0, 0, 0, 0, 227, 0, 0, 216, 0, 211,
	0, 211, 0, 47, 48, 49, 50, 51, 55, 4,
	20, 57, 17, 0, 0, 0, 62, 0, 0, 96,
	0, 30, 208, 0, 170, 232, 0, 0, 213, 213,
	0, 233, 232, 0, 233, 0, 0, 0, 0, 0,
	46, 24, 0, 19, 63, 65, 70, 232, 68, 69,
	106, 0, 0, 135, 136, 137, 0, 170, 0, 0,
	155, 0, 0, 173, 0, 175, 176, 177, 207, 158,
	159, 160, 156, 157, 162, 196, 0, 0, 104, 0,
	0, 0, 233, 0, 0, 0, 228, 38, 0, 41,
	0, 43, 212, 0, 233, 0, 52, 0, 66, 71,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 122, 123, 124, 125, 126, 127, 128, 109, 0,
	0, 0, 0, 133, 149, 0, 0, 0, 0, 120,
	0, 0, 174, 0, 163, 0, 0, 0, 104, 97,
	182, 0, 209, 210, 171, 172, 31, 0, 214, 233,
	233, 0, 0, 233, 224, 217, 218, 219, 220, 0,
	223, 42, 44, 45, 25, 0, 64, 72, 67, 107,
	108, 111, 112, 0, 130, 131, 0, 0, 0, 114,
	0, 118, 0, 138, 139, 140, 141, 142, 143, 144,
	145, 146, 147, 148, 110, 132, 0, 206, 133, 150,
	0, 0, 0, 0, 0, 168, 164, 0, 200, 0,
	203, 200, 0, 198, 182, 190, 0, 105, 233, 21,
	0, 32, 0, 33, 0, 0, 229, 39, 0, 225,
	0, 222, 104, 73, 80, 0, 92, 95, 0, 113,
	115, 0, 0, 119, 134, 151, 0, 153, 0, 0,
	0, 165, 0, 0, 0, 26, 0, 202, 204, 27,
	197, 0, 190, 29, 0, 0, 34, 0, 233, 233,
	230, 40, 0, 178, 0, 0, 83, 84, 0, 0,
	0, 0, 0, 52, 81, 0, 0, 0, 0, 129,
	0, 116, 152, 0, 0, 161, 169, 0, 0, 0,
	0, 199, 28, 191, 183, 184, 187, 22, 35, 36,
	233, 0, 221, 180, 0, 74, 77, 85, 0, 87,
	0, 89, 90, 91, 98, 82, 76, 93, 0, 117,
	154, 121, 166, 167, 0, 205, 0, 0, 186, 188,
	189, 37, 0, 182, 0, 0, 0, 0, 86, 88,
	75, 0, 0, 0, 94, 0, 192, 185, 231, 190,
	181, 179, 78, 0, 0, 0, 0, 201, 193, 0,
	0, 0, 0, 18, 0, 0, 79, 0, 102, 0,
	0, 194, 0, 99, 0, 100, 101, 0, 103, 195,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 114, 80, 70, 3,
	46, 113, 78, 76, 55, 77, 81, 79, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 112,
	48, 47, 49, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 72, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 71, 3, 50,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 51, 52, 53, 54, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
	68, 69, 73, 74, 75, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 101, 102, 103, 104, 105, 106,
	107, 108, 109, 110, 111,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:179
		{
			SetParseTree(yylex, yyDollar[1].positionedStatements)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:185
		{
			yyVAL.positionedStatements = PositionedStatements{}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:189
		{
			yyVAL.positionedStatements = PositionedStatements{PositionStatement{Start: getStatementStart(yylex), End: GetCurrentPos(yylex), Statement: yyDollar[2].statement}}
		}
	case 4:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:193
		{
			yyVAL.positionedStatements = append(yyDollar[1].positionedStatements, PositionStatement{Start: getStatementStart(yylex), End: GetCurrentPos(yylex), Statement: yyDollar[4].statement})
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:197
		{
			yyVAL.positionedStatements = yyDollar[1].positionedStatements
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:203
		{
			yyVAL.statement = yyDollar[1].selStmt
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:219
		{
			if s, ok := yyDollar[3].selStmt.(*Select); ok {
				s.With = yyDollar[2].withList
			}
			yyVAL.selStmt = yyDollar[3].selStmt
		}
	case 18:
		yyDollar = yyS[yypt-13 : yypt+1]
//line sql.y:224
		{
			yyVAL.selStmt = &Select{Comments: Comments(yyDollar[2].bytes2), Distinct: yyDollar[3].str, SelectExprs: yyDollar[4].selectExprs, From: yyDollar[7].tableExprs, FromComments: Comments(yyDollar[6].bytes2), Where: NewWhere(AST_WHERE, yyDollar[8].boolExpr), GroupBy: GroupBy(yyDollar[9].valExprs), Having: NewWhere(AST_HAVING, yyDollar[10].boolExpr), OrderBy: yyDollar[11].orderBy, Limit: yyDollar[12].limit, Lock: yyDollar[13].str}
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:228
		{
			yyVAL.selStmt = &Select{Comments: Comments(yyDollar[2].bytes2), Distinct: yyDollar[3].str, SelectExprs: yyDollar[4].selectExprs}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:232
		{
			yyVAL.selStmt = &Union{Type: yyDollar[2].str, Left: yyDollar[1].selStmt, Right: yyDollar[3].selStmt}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:238
		{
			yyVAL.selStmt = yyDollar[1].selStmt
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:240
		{
			yyVAL.selStmt = yyDollar[2].selStmt
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:244
		{
			yyVAL.withList = []*WithCTE{yyDollar[1].withCTE}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:248
		{
			yyVAL.withList = append(yyDollar[1].withList, yyDollar[3].withCTE)
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:254
		{
			yyVAL.withCTE = &WithCTE{Name: yyDollar[1].bytes, Select: yyDollar[4].selStmt}
		}
	case 26:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:260
		{
			yyVAL.statement = &Insert{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Columns: yyDollar[5].columns, Rows: yyDollar[6].insRows, OnDup: OnDup(yyDollar[7].updateExprs)}
		}
	case 27:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:264
		{
			cols := make(Columns, 0, len(yyDollar[6].updateExprs))
			vals := make(ValTuple, 0, len(yyDollar[6].updateExprs))
			for _, col := range yyDollar[6].updateExprs {
				cols = append(cols, &NonStarExpr{Expr: col.Name})
				vals = append(vals, col.Expr)
			}
			yyVAL.statement = &Insert{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Columns: cols, Rows: Values{vals}, OnDup: OnDup(yyDollar[7].updateExprs)}
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:276
		{
			yyVAL.statement = &Update{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[3].tableName, Exprs: yyDollar[5].updateExprs, Where: NewWhere(AST_WHERE, yyDollar[6].boolExpr), OrderBy: yyDollar[7].orderBy, Limit: yyDollar[8].limit}
		}
	case 29:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:282
		{
			yyVAL.statement = &Delete{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Where: NewWhere(AST_WHERE, yyDollar[5].boolExpr), OrderBy: yyDollar[6].orderBy, Limit: yyDollar[7].limit}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:288
		{
			yyVAL.statement = &Set{Comments: Comments(yyDollar[2].bytes2), Exprs: yyDollar[3].updateExprs}
		}
	case 31:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:294
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[4].bytes}
		}
	case 32:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:298
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[5].bytes, Temporary: true}
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:302
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[5].bytes, Temporary: true}
		}
	case 34:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:306
		{
			yyVAL.statement = &CreateTableAsSelect{Table: yyDollar[4].bytes, Select: yyDollar[6].selStmt}
		}
	case 35:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:310
		{
			yyVAL.statement = &CreateTableAsSelect{Table: yyDollar[5].bytes, Select: yyDollar[7].selStmt, Temporary: true}
		}
	case 36:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:314
		{
			yyVAL.statement = &CreateTableAsSelect{Table: yyDollar[5].bytes, Select: yyDollar[7].selStmt, Temporary: true}
		}
	case 37:
		yyDollar = yyS[yypt-9 : yypt+1]
//line sql.y:318
		{
			// Change this to an alter statement
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[7].bytes, NewName: yyDollar[7].bytes}
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:323
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[3].bytes}
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:329
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[4].bytes, NewName: yyDollar[4].bytes}
		}
	case 40:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:333
		{
			// Change this to a rename statement
			yyVAL.statement = &DDL{Action: AST_RENAME, Table: yyDollar[4].bytes, NewName: yyDollar[7].bytes}
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:338
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[3].bytes, NewName: yyDollar[3].bytes}
		}
	case 42:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:344
		{
			yyVAL.statement = &DDL{Action: AST_RENAME, Table: yyDollar[3].bytes, NewName: yyDollar[5].bytes}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:350
		{
			yyVAL.statement = &DDL{Action: AST_DROP, Table: yyDollar[4].bytes}
		}
	case 44:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:354
		{
			// Change this to an alter statement
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[5].bytes, NewName: yyDollar[5].bytes}
		}
	case 45:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:359
		{
			yyVAL.statement = &DDL{Action: AST_DROP, Table: yyDollar[4].bytes}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:365
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[3].bytes, NewName: yyDollar[3].bytes}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:371
		{
			yyVAL.statement = &Other{}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:375
		{
			yyVAL.statement = &Other{}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:379
		{
			yyVAL.statement = &Other{}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:383
		{
			yyVAL.statement = &Other{}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:387
		{
			yyVAL.statement = &Other{}
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:392
		{
			SetAllowComments(yylex, true)
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:396
		{
			yyVAL.bytes2 = yyDollar[2].bytes2
			SetAllowComments(yylex, false)
		}
	case 54:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:402
		{
			yyVAL.bytes2 = nil
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:406
		{
			yyVAL.bytes2 = append(yyDollar[1].bytes2, yyDollar[2].bytes)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:412
		{
			yyVAL.str = AST_UNION
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:416
		{
			yyVAL.str = AST_UNION_ALL
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:420
		{
			yyVAL.str = AST_SET_MINUS
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:424
		{
			yyVAL.str = AST_EXCEPT
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:428
		{
			yyVAL.str = AST_INTERSECT
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:433
		{
			yyVAL.str = ""
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:437
		{
			yyVAL.str = AST_DISTINCT
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:443
		{
			yyVAL.selectExprs = SelectExprs{yyDollar[1].selectExpr}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:447
		{
			yyVAL.selectExprs = append(yyVAL.selectExprs, yyDollar[3].selectExpr)
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:453
		{
			yyVAL.selectExpr = &StarExpr{}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:457
		{
			yyVAL.selectExpr = &NonStarExpr{Expr: yyDollar[1].expr, As: yyDollar[2].bytes}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:461
		{
			yyVAL.selectExpr = &StarExpr{TableName: yyDollar[1].bytes}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:467
		{
			yyVAL.expr = yyDollar[1].boolExpr
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:471
		{
			yyVAL.expr = yyDollar[1].valExpr
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:476
		{
			yyVAL.bytes = nil
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:480
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:484
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:490
		{
			yyVAL.tableExprs = TableExprs{yyDollar[1].tableExpr}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:494
		{
			yyVAL.tableExprs = append(yyVAL.tableExprs, yyDollar[3].tableExpr)
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:500
		{
			yyVAL.tableExpr = &AliasedTableExpr{Position: GetCurrentPos(yylex), Expr: yyDollar[1].smTableExpr, As: yyDollar[2].bytes, Hints: yyDollar[4].indexHints}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:504
		{
			yyVAL.tableExpr = &ParenTableExpr{Expr: yyDollar[2].tableExpr}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:508
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr}
		}
	case 78:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:512
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr, On: yyDollar[5].boolExpr}
		}
	case 79:
		yyDollar = yyS[yypt-7 : yypt+1]
//line sql.y:516
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr, Using: yyDollar[6].columns}
		}
	case 80:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:521
		{
			yyVAL.bytes = nil
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:525
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:529
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:535
		{
			yyVAL.str = AST_JOIN
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:539
		{
			yyVAL.str = AST_STRAIGHT_JOIN
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:543
		{
			yyVAL.str = AST_LEFT_JOIN
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:547
		{
			yyVAL.str = AST_LEFT_JOIN
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:551
		{
			yyVAL.str = AST_RIGHT_JOIN
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:555
		{
			yyVAL.str = AST_RIGHT_JOIN
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:559
		{
			yyVAL.str = AST_JOIN
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:563
		{
			yyVAL.str = AST_CROSS_JOIN
		}
	case 91:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:567
		{
			yyVAL.str = AST_NATURAL_JOIN
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:573
		{
			yyVAL.smTableExpr = &TableName{Name: yyDollar[1].bytes}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:577
		{
			yyVAL.smTableExpr = &TableName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:581
		{
			yyVAL.smTableExpr = &TableFunc{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:585
		{
			yyVAL.smTableExpr = yyDollar[1].subquery
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:591
		{
			yyVAL.tableName = &TableName{Name: yyDollar[1].bytes}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:595
		{
			yyVAL.tableName = &TableName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 98:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:600
		{
			yyVAL.indexHints = nil
		}
	case 99:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:604
		{
			yyVAL.indexHints = &IndexHints{Type: AST_USE, Indexes: yyDollar[4].bytes2}
		}
	case 100:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:608
		{
			yyVAL.indexHints = &IndexHints{Type: AST_IGNORE, Indexes: yyDollar[4].bytes2}
		}
	case 101:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:612
		{
			yyVAL.indexHints = &IndexHints{Type: AST_FORCE, Indexes: yyDollar[4].bytes2}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:618
		{
			yyVAL.bytes2 = [][]byte{yyDollar[1].bytes}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:622
		{
			yyVAL.bytes2 = append(yyDollar[1].bytes2, yyDollar[3].bytes)
		}
	case 104:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:627
		{
			yyVAL.boolExpr = nil
		}
	case 105:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:631
		{
			yyVAL.boolExpr = yyDollar[2].boolExpr
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:638
		{
			yyVAL.boolExpr = &AndExpr{Left: yyDollar[1].boolExpr, Right: yyDollar[3].boolExpr}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:642
		{
			yyVAL.boolExpr = &OrExpr{Left: yyDollar[1].boolExpr, Right: yyDollar[3].boolExpr}
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:646
		{
			yyVAL.boolExpr = &NotExpr{Expr: yyDollar[2].boolExpr}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:650
		{
			yyVAL.boolExpr = &ParenBoolExpr{Expr: yyDollar[2].boolExpr}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:656
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: yyDollar[2].str, Right: yyDollar[3].valExpr}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:660
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_IN, Right: yyDollar[3].colTuple}
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:664
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_NOT_IN, Right: yyDollar[4].colTuple}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:668
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_LIKE, Right: yyDollar[3].valExpr}
		}
	case 115:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:672
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_NOT_LIKE, Right: yyDollar[4].valExpr}
		}
	case 116:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:676
		{
			yyVAL.boolExpr = &RangeCond{Left: yyDollar[1].valExpr, Operator: AST_BETWEEN, From: yyDollar[3].valExpr, To: yyDollar[5].valExpr}
		}
	case 117:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:680
		{
			yyVAL.boolExpr = &RangeCond{Left: yyDollar[1].valExpr, Operator: AST_NOT_BETWEEN, From: yyDollar[4].valExpr, To: yyDollar[6].valExpr}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:684
		{
			yyVAL.boolExpr = &NullCheck{Operator: AST_IS_NULL, Expr: yyDollar[1].valExpr}
		}
	case 119:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:688
		{
			yyVAL.boolExpr = &NullCheck{Operator: AST_IS_NOT_NULL, Expr: yyDollar[1].valExpr}
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:692
		{
			yyVAL.boolExpr = &ExistsExpr{Subquery: yyDollar[2].subquery}
		}
	case 121:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:696
		{
			yyVAL.boolExpr = &KeyrangeExpr{Start: yyDollar[3].valExpr, End: yyDollar[5].valExpr}
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:702
		{
			yyVAL.str = AST_EQ
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:706
		{
			yyVAL.str = AST_LT
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:710
		{
			yyVAL.str = AST_GT
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:714
		{
			yyVAL.str = AST_LE
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:718
		{
			yyVAL.str = AST_GE
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:722
		{
			yyVAL.str = AST_NE
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:726
		{
			yyVAL.str = AST_NSE
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:732
		{
			yyVAL.colTuple = ValTuple(yyDollar[2].valExprs)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:736
		{
			yyVAL.colTuple = yyDollar[1].subquery
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:740
		{
			yyVAL.colTuple = ListArg(yyDollar[1].bytes)
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:746
		{
			yyVAL.subquery = &Subquery{yyDollar[2].selStmt}
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:752
		{
			yyVAL.valExprs = ValExprs{yyDollar[1].valExpr}
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:756
		{
			yyVAL.valExprs = append(yyDollar[1].valExprs, yyDollar[3].valExpr)
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:762
		{
			yyVAL.valExpr = yyDollar[1].valExpr
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:766
		{
			yyVAL.valExpr = yyDollar[1].colName
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:770
		{
			yyVAL.valExpr = yyDollar[1].rowTuple
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:774
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITAND, Right: yyDollar[3].valExpr}
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:778
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITOR, Right: yyDollar[3].valExpr}
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:782
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITXOR, Right: yyDollar[3].valExpr}
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:786
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: "||", Right: yyDollar[3].valExpr}
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:790
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: "->", Right: yyDollar[3].valExpr}
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:794
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: "->>", Right: yyDollar[3].valExpr}
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:798
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_PLUS, Right: yyDollar[3].valExpr}
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:802
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MINUS, Right: yyDollar[3].valExpr}
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:806
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MULT, Right: yyDollar[3].valExpr}
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:810
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_DIV, Right: yyDollar[3].valExpr}
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:814
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MOD, Right: yyDollar[3].valExpr}
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:818
		{
			if num, ok := yyDollar[2].valExpr.(NumVal); ok {
				switch yyDollar[1].byt {
				case '-':
					yyVAL.valExpr = append(NumVal("-"), num...)
				case '+':
					yyVAL.valExpr = num
				default:
					yyVAL.valExpr = &UnaryExpr{Operator: yyDollar[1].byt, Expr: yyDollar[2].valExpr}
				}
			} else {
				yyVAL.valExpr = &UnaryExpr{Operator: yyDollar[1].byt, Expr: yyDollar[2].valExpr}
			}
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:833
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes}
		}
	case 151:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:837
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 152:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:841
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Distinct: true, Exprs: yyDollar[4].selectExprs}
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:845
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 154:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:849
		{
			yyVAL.valExpr = &FuncExpr{Name: []byte("cast"), Exprs: SelectExprs{&NonStarExpr{Expr: yyDollar[3].valExpr}}}
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:853
		{
			yyVAL.valExpr = yyDollar[1].caseExpr
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:859
		{
			yyVAL.bytes = IF_BYTES
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:863
		{
			yyVAL.bytes = VALUES_BYTES
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:869
		{
			yyVAL.byt = AST_UPLUS
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:873
		{
			yyVAL.byt = AST_UMINUS
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:877
		{
			yyVAL.byt = AST_TILDA
		}
	case 161:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:883
		{
			yyVAL.caseExpr = &CaseExpr{Expr: yyDollar[2].valExpr, Whens: yyDollar[3].whens, Else: yyDollar[4].valExpr}
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:888
		{
			yyVAL.valExpr = nil
		}
	case 163:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:892
		{
			yyVAL.valExpr = yyDollar[1].valExpr
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:898
		{
			yyVAL.whens = []*When{yyDollar[1].when}
		}
	case 165:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:902
		{
			yyVAL.whens = append(yyDollar[1].whens, yyDollar[2].when)
		}
	case 166:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:908
		{
			yyVAL.when = &When{Cond: yyDollar[2].boolExpr, Val: yyDollar[4].valExpr}
		}
	case 167:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:912
		{
			/* Bare value in WHEN: treat as truth test (IS NOT NULL) */
			yyVAL.when = &When{Cond: &NullCheck{Operator: AST_IS_NOT_NULL, Expr: yyDollar[2].valExpr}, Val: yyDollar[4].valExpr}
		}
	case 168:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:918
		{
			yyVAL.valExpr = nil
		}
	case 169:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:922
		{
			yyVAL.valExpr = yyDollar[2].valExpr
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:928
		{
			yyVAL.colName = &ColName{Name: yyDollar[1].bytes}
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:932
		{
			yyVAL.colName = &ColName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:936
		{
			yyVAL.colName = &ColName{Qualifier: yyDollar[1].bytes, Name: []byte("key")}
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:942
		{
			yyVAL.valExpr = StrVal(yyDollar[1].bytes)
		}
	case 174:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:946
		{
			yyVAL.valExpr = ValArg(":v$" + string(yyDollar[2].bytes))
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:950
		{
			yyVAL.valExpr = NumVal(yyDollar[1].bytes)
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:954
		{
			yyVAL.valExpr = ValArg(yyDollar[1].bytes)
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:958
		{
			yyVAL.valExpr = &NullVal{}
		}
	case 178:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:963
		{
			yyVAL.valExprs = nil
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:967
		{
			yyVAL.valExprs = yyDollar[3].valExprs
		}
	case 180:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:972
		{
			yyVAL.boolExpr = nil
		}
	case 181:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:976
		{
			yyVAL.boolExpr = yyDollar[2].boolExpr
		}
	case 182:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:981
		{
			yyVAL.orderBy = nil
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:985
		{
			yyVAL.orderBy = yyDollar[3].orderBy
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:991
		{
			yyVAL.orderBy = OrderBy{yyDollar[1].order}
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:995
		{
			yyVAL.orderBy = append(yyDollar[1].orderBy, yyDollar[3].order)
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1001
		{
			yyVAL.order = &Order{Expr: yyDollar[1].valExpr, Direction: yyDollar[2].str}
		}
	case 187:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1006
		{
			yyVAL.str = AST_ASC
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1010
		{
			yyVAL.str = AST_ASC
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1014
		{
			yyVAL.str = AST_DESC
		}
	case 190:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1019
		{
			yyVAL.limit = nil
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1023
		{
			yyVAL.limit = &Limit{Rowcount: yyDollar[2].valExpr}
		}
	case 192:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:1027
		{
			yyVAL.limit = &Limit{Offset: yyDollar[2].valExpr, Rowcount: yyDollar[4].valExpr}
		}
	case 193:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1032
		{
			yyVAL.str = ""
		}
	case 194:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1036
		{
			yyVAL.str = AST_FOR_UPDATE
		}
	case 195:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:1040
		{
			if !bytes.Equal(yyDollar[3].bytes, SHARE) {
				yylex.Error("expecting share")
				return 1
			}
			if !bytes.Equal(yyDollar[4].bytes, MODE) {
				yylex.Error("expecting mode")
				return 1
			}
			yyVAL.str = AST_SHARE_MODE
		}
	case 196:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1053
		{
			yyVAL.columns = nil
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1057
		{
			yyVAL.columns = yyDollar[2].columns
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1063
		{
			yyVAL.columns = Columns{&NonStarExpr{Expr: yyDollar[1].colName}}
		}
	case 199:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1067
		{
			yyVAL.columns = append(yyVAL.columns, &NonStarExpr{Expr: yyDollar[3].colName})
		}
	case 200:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1072
		{
			yyVAL.updateExprs = nil
		}
	case 201:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:1076
		{
			yyVAL.updateExprs = yyDollar[5].updateExprs
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1082
		{
			yyVAL.insRows = yyDollar[2].values
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1086
		{
			yyVAL.insRows = yyDollar[1].selStmt
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1092
		{
			yyVAL.values = Values{yyDollar[1].rowTuple}
		}
	case 205:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1096
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].rowTuple)
		}
	case 206:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1102
		{
			yyVAL.rowTuple = ValTuple(yyDollar[2].valExprs)
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1106
		{
			yyVAL.rowTuple = yyDollar[1].subquery
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1112
		{
			yyVAL.updateExprs = UpdateExprs{yyDollar[1].updateExpr}
		}
	case 209:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1116
		{
			yyVAL.updateExprs = append(yyDollar[1].updateExprs, yyDollar[3].updateExpr)
		}
	case 210:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1122
		{
			yyVAL.updateExpr = &UpdateExpr{Name: yyDollar[1].colName, Expr: yyDollar[3].valExpr}
		}
	case 211:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1127
		{
			yyVAL.empty = struct{}{}
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1129
		{
			yyVAL.empty = struct{}{}
		}
	case 213:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1132
		{
			yyVAL.empty = struct{}{}
		}
	case 214:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1134
		{
			yyVAL.empty = struct{}{}
		}
	case 215:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1137
		{
			yyVAL.empty = struct{}{}
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1139
		{
			yyVAL.empty = struct{}{}
		}
	case 217:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1143
		{
			yyVAL.empty = struct{}{}
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1145
		{
			yyVAL.empty = struct{}{}
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1147
		{
			yyVAL.empty = struct{}{}
		}
	case 220:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1149
		{
			yyVAL.empty = struct{}{}
		}
	case 221:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:1151
		{
			yyVAL.empty = struct{}{}
		}
	case 222:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1153
		{
			yyVAL.empty = struct{}{}
		}
	case 223:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1155
		{
			yyVAL.empty = struct{}{}
		}
	case 224:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1158
		{
			yyVAL.empty = struct{}{}
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1160
		{
			yyVAL.empty = struct{}{}
		}
	case 226:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1163
		{
			yyVAL.empty = struct{}{}
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1165
		{
			yyVAL.empty = struct{}{}
		}
	case 228:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1168
		{
			yyVAL.empty = struct{}{}
		}
	case 229:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:1170
		{
			yyVAL.empty = struct{}{}
		}
	case 230:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1173
		{
			yyVAL.empty = struct{}{}
		}
	case 231:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:1175
		{
			yyVAL.empty = struct{}{}
		}
	case 232:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:1179
		{
			yyVAL.bytes = bytes.ToLower(yyDollar[1].bytes)
		}
	case 233:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:1184
		{
			ForceEOF(yylex)
		}
	}
	goto yystack /* stack new state and value */
}
